WebTraiCay/Areas/Admin/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.IO;
using System.Web.Mvc;
using WebTraiCay.Models;
using WebTraiCay.Common;

namespace WebTraiCay.Areas.Admin.Controllers
{
    [CustomAuthorizeAttribute(RoleID = "ADMIN")]
    public class SliderController : BaseController
    {
        private WebTraiCayDbContext db = new WebTraiCayDbContext();

        // GET: Admin/Slider
        public ActionResult Index()
        {
            var list = db.Sliders.Where(m => m.status != 0).OrderByDescending(m => m.ID).ToList();
            return View(list);
        }

        // GET: Admin/Slider/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mslider mslider = db.Sliders.Find(id);
            if (mslider == null)
            {
                return HttpNotFound();
            }
            return View(mslider);
        }

        // GET: Admin/Slider/Create
        public ActionResult Create()
        {
            ViewBag.listCate = db.Sliders.Where(m => m.status != 0 ).ToList();
            return View();
        }

        // POST: Admin/Slider/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Mslider mslider, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                file = Request.Files["img"];
                string filename = file.FileName.ToString();
                string slug = Mystring.ToSlug(mslider.name.ToString());
                string ExtensionFile = Mystring.GetFileExtension(filename);
                string namefilenew = slug + "." + ExtensionFile;
                var path = Path.Combine(Server.MapPath("~/public/images"), namefilenew);

                file.SaveAs(path);
                mslider.url = slug;
                mslider.img = namefilenew;
                mslider.created_at = DateTime.Now;
                mslider.updated_at = DateTime.Now;
                mslider.created_by = int.Parse(Session["Admin_id"].ToString());
                mslider.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.Sliders.Add(mslider);
                db.SaveChanges();
                Message.set_flash("Thêm thành công", "success");
                return RedirectToAction("Index");
            }
            Message.set_flash("Thêm thất bại", "danger");
            return View(mslider);
        }
        public ActionResult Edit(int? id)
        {
            ViewBag.listCate = db.Sliders.Where(m => m.status != 0).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mslider mslider = db.Sliders.Find(id);
            if (mslider == null)
            {
                return HttpNotFound();
            }
           
            return View(mslider);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Mslider mslider)
        {
           
            if (ModelState.IsValid)
            {
                string slug = Mystring.ToSlug(mslider.name.ToString());
                HttpPostedFileBase file = Request.Files["img"];
                string filename = file.FileName.ToString();
                if (filename.Equals("") == false)
                {
                    string ExtensionFile = Mystring.GetFileExtension(filename);
                    string namefilenew = slug + "." + ExtensionFile;
                    var path = Path.Combine(Server.MapPath("~/public/images"), namefilenew);
                    file.SaveAs(path);
                    mslider.img = namefilenew;
                }
                mslider.url = slug;
                mslider.updated_at = DateTime.Now;
                mslider.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.Entry(mslider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.listCate = db.Sliders.Where(m => m.status != 0).ToList();
            return View(mslider);
        }
        public ActionResult Status(int id)
        {
            Mslider mslider = db.Sliders.Find(id);
            mslider.status = (mslider.status == 1) ? 2 : 1;
            mslider.updated_at = DateTime.Now;
            mslider.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mslider).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Thay đổi trang thái thành công", "success");
            return RedirectToAction("Index");
        }
        public ActionResult trash()
        {
            var list = db.Sliders.Where(m => m.status == 0).ToList();
            return View("Trash", list);
        }
        public ActionResult Deltrash(int id)
        {
            Mslider mslider = db.Sliders.Find(id);
            mslider.status = 0;
            mslider.updated_at = DateTime.Now;
            mslider.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mslider).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Xóa thành côngss", "success");
            return RedirectToAction("Index");
        }
        public ActionResult Retrash(int id)
        {
            Mslider mslider = db.Sliders.Find(id);
            mslider.status = 2;
            mslider.updated_at = DateTime.Now;
            mslider.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mslider).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("khôi phục thành công", "success");
            return RedirectToAction("trash");
        }
        public ActionResult deleteTrash(int id)
        {
            Mslider mslider = db.Sliders.Find(id);
            db.Sliders.Remove(mslider);
            db.SaveChanges();
            Message.set_flash("Đã xóa vĩnh viễn 1 Ảnh bìa", "success");
            return RedirectToAction("trash");
        }

    }
}

WebTraiCay/Areas/Admin/Views/Slider/Create.cshtml
@model WebTraiCay.Models.Mslider

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    List<SelectListItem> status = new List<SelectListItem>();
    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Ẩn" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Hiện" };
    status.Add(statusitem1);
    status.Add(statusitem2);


    SelectListItem listorderitem;
    List<SelectListItem> listorder = new List<SelectListItem>();
    foreach (var item in ViewBag.listCate)
    {
        listorderitem = new SelectListItem() { Value = item.orders + "", Text = "Sau [" + item.name + "]" };
        listorder.Add(listorderitem);

    }

    List<SelectListItem> position = new List<SelectListItem>();

    SelectListItem position1 = new SelectListItem() { Value = "SliderShow", Text = "SliderShow" };
    position.Add(position1);
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0 bg-light">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thêm Ảnh Bìa</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                        <li class="breadcrumb-item active">Thêm ảnh bìa</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

  
    <section class="pt-2 container">
        @Html.Partial("_MessgeAlert")
        <div class="container bg-white p-4 ">

            @using (Html.BeginForm("Create", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class=" row ">
                    <div class="col-md-4">  </div>
                    <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> THÊM ẢNH BÌA</h3> </div>
                    <div class="col-md-4 ">
                        <div class="float-right">
                            <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                            <a href="~/admin/category" class="btn btn-sm bg-dodam text-white"><i class="far fa-window-close"></i> Hủy</a>
                        </div>
                    </div>
                </div>
                <div class=" row ">
                    <div class="col-md-8">
                        <div>
                            <label for="psw"><span>Tên Slider</span></label>
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", placeholder = "Tên slider", required = "required" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><span>Loại Slider</span></label>
                            @Html.DropDownListFor(model => model.position, position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <label for="psw"><span>Chọn vị trí hiển thị</span></label>
                            @Html.DropDownListFor(model => model.orders, listorder, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.orders, "", new { @class = "text-danger" })
                        </div>
                        <label for="psw"><span>Hình ảnh Slider</span></label>
                        <input type="file" name="img" class="form-control" />
                        @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                        <div>
                            <label for="psw"><span>Trang Thái</span></label>
                            @Html.DropDownListFor(model => model.status, status, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>
            }
        </div>
    </section>
    <script>
        $("#slider").addClass("active");
    </script>

WebTraiCay/Areas/Admin/Views/Slider/Edit.cshtml
@model WebTraiCay.Models.Mslider

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    List<SelectListItem> status = new List<SelectListItem>();
    SelectListItem statusitem1 = new SelectListItem() { Value = "1", Text = "Hiện" };
    SelectListItem statusitem2 = new SelectListItem() { Value = "2", Text = "Ẩn" };
    status.Add(statusitem1);
    status.Add(statusitem2);


    SelectListItem listorderitem;
    List<SelectListItem> listorder = new List<SelectListItem>();
    foreach (var item in ViewBag.listCate)
    {
        listorderitem = new SelectListItem() { Value = item.orders + "", Text = "Sau [" + item.name + "]" };
        listorder.Add(listorderitem);

    }

    List<SelectListItem> position = new List<SelectListItem>();

    SelectListItem position1 = new SelectListItem() { Value = "SliderShow", Text = "SliderShow" };
    position.Add(position1);
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0 bg-light">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Cập Nhật Ảnh Bìa</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/Admin">Home</a></li>
                        <li class="breadcrumb-item active">Thêm sản phẩm</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


    <section class="pt-2">
        @Html.Partial("_MessgeAlert")
        <div class="container bg-white pt-4 ">

            @using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ID)
                @Html.HiddenFor(model => model.img)
                @Html.HiddenFor(model => model.created_at)
                @Html.HiddenFor(model => model.created_by)
                <div class=" row ">
                    <div class="col-md-4">  </div>
                    <div class="col-md-4"> <h3 class="text-center font-weight-bold text-success "> THÊM LOẠI SẢN PHẨM</h3> </div>
                    <div class="col-md-4 ">
                        <div class="float-right">
                            <button class="btn btn-sm bg-success text-white"><i class="far fa-save"></i> Lưu</button>
                            <a href="~/admin/category" class="btn btn-sm bg-dodam text-white"><i class="far fa-window-close"></i> Hủy</a>
                        </div>
                    </div>
                </div>
                <div class=" row ">
                    <div class="col-md-8">
                        <div>
                            <label for="psw"><b class="text-secondary ">Tên Slider</b></label>
                            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                        </div>
                        <div>
                            <label for="psw"><b class="text-secondary ">Loại Slider</b></label>
                            @Html.DropDownListFor(model => model.position, position, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })

                        </div>
                    </div>
                    <div class="col-md-4">
                        <div>
                            <label for="psw"><b class="text-secondary ">Chọn vị trí hiển thị</b></label>
                            @Html.DropDownListFor(model => model.orders, listorder, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.orders, "", new { @class = "text-danger" })
                        </div>
                        <label for="psw"><b class="text-secondary ">Hình ảnh Slider</b></label>
                        <input type="file" name="img" class="form-control" />
                        @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
                        <div>
                            <label for="psw"><b class="text-secondary ">Trang Thái</b></label>
                            @Html.DropDownListFor(model => model.status, status, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                        </div>
                    </div>


                </div>
            }
        </div>
    </section>
    <script>
        $("#slider").addClass("active");
    </script>

WebTraiCay/Areas/Admin/Views/Slider/Index.cshtml
@model IEnumerable<WebTraiCay.Models.Mslider>

@{
    ViewBag.Title = "Slider";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Quản Lý Ảnh Bìa</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quản Lý Sản Phẩm</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


  
    <section class="container-fluid ">
        <div class=" bg-white card  ">
            <div class="row justify-content-end">
                <div class="col-md-6 ">
                    <div class=" pt-1 ml-5 float-right mr-3">
                        <a class="text-white btn-sm btn-success" href="~/admin/slider/Create">Add slider <i class="fas fa-plus"></i></a>
                        <a class="text-white btn-sm btn-success " href="~/admin/slider/trash">Thùng rác<i class="fas fa-trash"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9  w-100 ">
                    @Html.Partial("_MessgeAlert")
                </div>
                <div class="col-md-12 p-3">

                    <table id="myTable1" class="table px-3 table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Hình</th>
                                <th width="30%">Tên slider</th>
                                <th>Ngày Tạo</th>
                                <th>Chức Năng</th>
                                <th>ID</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td><img width="50px" src="~/public/images/@Html.DisplayFor(modelItem => item.img)"></td>
                                    <td> @Html.DisplayFor(modelItem => item.name)</td>
                                    <td style="font-size:14px;">@Html.DisplayFor(modelItem => item.created_at)</td>
                                    <td>
                                        @if (item.status == 1)
                                        {
                                            <a class="btn btn-sm btn-light text-success border a33" href="@Url.Action("Status", "Slider", new { id = item.ID })"> <i class="fas fa-toggle-on"></i> </a>
                                        }
                                        else
                                        {
                                            <a class="btn btn-sm btn-light text-danger border a33" href="@Url.Action("Status", "Slider", new { id = item.ID })"> <i class="fas fa-toggle-off"></i> </a>
                                        }


                                        <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("Deltrash", "Slider", new { id = item.ID })"> <i class="far fa-trash-alt"></i></a>
                                        <a class="btn btn-sm btn-light text-warning border" href="@Url.Action("Edit", "Slider", new { id = item.ID })">
                                            <i class="far fa-edit"></i>
                                        </a>
                                    </td>
                                    <td class="text-cam ">@Html.DisplayFor(modelItem => item.ID)</td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
        $("#slider").addClass("active");
    </script>

WebTraiCay/Areas/Admin/Views/Slider/Trash.cshtml
@model IEnumerable<WebTraiCay.Models.Mslider>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@Html.Partial("~/Areas/Admin/Views/Shared/_topMenu.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_leftMenu.cshtml")
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row m-0">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">Thùng Rác Ảnh Bìa</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Quản Lý Sản Phẩm</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->


  
    <section class="container-fluid ">
        <div class=" bg-white card  ">
            <div class="row justify-content-end">
                <div class="col-md-3">
                    <div class=" pt-1 ml-5 float-right mr-3">
                        <a class="text-white btn-sm btn-success " href="~/admin/Slider">Thoát</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-9  w-100 ">
                    @Html.Partial("_MessgeAlert")
                </div>
                <div class="col-md-12 p-3">

                    <table class="table px-3 table-striped table-bordered dt-responsive nowrap">
                        <thead>
                            <tr>
                                <th>Hình ảnh</th>
                                <th>tên slider</th>
                                <th>position</th>
                                <th>Ngày Tạo</th>
                                <th>Chức Năng</th>
                                <th>ID</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td><img width="20px" src="~/public/images/@Html.DisplayFor(modelItem => item.img)"></td>
                                    <td><a class=" font-weight-bold card-link " href=""> @Html.DisplayFor(modelItem => item.name)</a></td>
                                    <td width="15%">  @Html.DisplayFor(modelItem => item.position)</td>
                                    <td>@Html.DisplayFor(modelItem => item.created_at)</td>
                                    <td>
                                        <a class="btn btn-sm btn-light text-success border" href="@Url.Action("Retrash", "Slider", new { id = item.ID })"> <i class="fas fa-undo"></i></a>
                                        <a class="btn btn-sm btn-light text-danger border" href="@Url.Action("deleteTrash", "Slider", new { id = item.ID })">
                                            <i class="fas fa-trash-alt"></i>
                                        </a>
                                    </td>
                                    <td class="text-cam">@Html.DisplayFor(modelItem => item.ID)</td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </section>

    <script>
        $("#slider").addClass("active");
    </script>